import type { Metadata } from "next";
import "./globals.css";
import Provider from "./components/Provider";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "TaleWhirl",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Header />
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
