import type { Metadata } from "next";
import "./globals.css";
import Provider from "./components/Provider";
import Header from "./components/Header";
import { Theme, ThemePanel } from "@radix-ui/themes";
import ActivateAccount from "./components/ActivateAccount";

export const metadata: Metadata = {
  title: "TaleWhirl",
  description: "Generated by create next app",
};
/**
 * TODO - add the theme for the radix ui
 *
 */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Theme accentColor="amber" grayColor="olive" radius="small">
          <Provider>
            <Header />
            {/* <ActivateAccount /> */}
            <main>{children}</main>
          </Provider>
        </Theme>
      </body>
    </html>
  );
}
